name: Self-Healing CI/CD

on:
  workflow_dispatch:

jobs:
  self_heal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install openai github

    - name: Run self-healing script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python self_heal.py

    - name: Slack notification (optional)
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Self-healing workflow completed. PR created with the fix!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
